import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "fr" | "en" | "pt" | "es" | "it" | "ln" | "el" | "ko" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("fr");

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations["fr"]?.[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar
    "nav.learn": "Apprendre",
    "nav.lessons": "Leçons",
    "nav.vocabulary": "Vocabulaire",
    "nav.stories": "Histoires",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Se connecter",
    "nav.goPremium": "Passer Premium",
    "nav.managePlan": "Gérer l'abonnement",

    // Hero
    "hero.subtitle": "Nzo Mikanda — La Maison du Savoir",
    "hero.description": "Découvrez la langue sacrée du peuple Kongo à travers le vocabulaire, les histoires et l'art ancestral du Kilolaka — avec des traductions en français, anglais, portugais, italien, espagnol, lingala, grec et coréen.",
    "hero.startLearning": "Commencer à apprendre",
    "hero.exploreVocabulary": "Explorer le vocabulaire",

    // LearningPaths
    "paths.eyebrow": "Votre parcours d'apprentissage",
    "paths.title": "Trois voies vers la maîtrise",
    "paths.vocab.title": "Vocabulaire",
    "paths.vocab.desc": "Apprenez les mots et expressions essentiels en Kikongo Lari avec translittération latine, et traductions en français, anglais et portugais.",
    "paths.vocab.items": "Salutations & Expressions,Famille & Personnes,Nature & Animaux,Corps & Santé",
    "paths.stories.title": "Histoires",
    "paths.stories.desc": "Lisez des histoires bilingues comme les aventures de Nsayi — plongez dans la culture Kongo à travers le récit.",
    "paths.stories.items": "Nsayi à l'école,Nsayi dans la savane,Contes culturels,Histoires pour enfants",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Explorez l'art sacré de décomposer le Kikongo en codes énergétiques — la langue comme carte cosmologique.",
    "paths.kilolaka.items": "Analyse morphémique,Séries B & F,Axe D & G,Écriture Mandombe",

    // Vocabulary
    "vocab.eyebrow": "Mazita — Vocabulaire",
    "vocab.title": "Mots et expressions essentiels",
    "vocab.subtitle": "Chaque mot est en Kikongo Lari avec traductions en français, anglais et portugais — les langues parlées à travers la diaspora Kongo.",
    "vocab.freeWords": "mots gratuits",
    "vocab.premium": "premium",
    "vocab.more": "Plus de mots",

    // Stories
    "stories.eyebrow": "Binsamu — Histoires",
    "stories.title": "Apprendre par les histoires",
    "stories.storySubtitle": "Nsayi à l'école et à la forêt",
    "stories.storyDesc": "Une bande dessinée bilingue — français, anglais et portugais",
    "stories.storyDescShort": "Nsayi at School and in the Forest",
    "stories.continue": "Continuer l'histoire de Nsayi",
    "stories.end": "Fin de l'histoire",

    // Kilolaka
    "kilolaka.eyebrow": "Connaissance profonde",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "L'art de décomposer le Kikongo en conscience sacrée — chaque syllabe est un code énergétique.",
    "kilolaka.bSeries": "Série B : États de l'être",
    "kilolaka.advanced": "Modules Kilolaka avancés",
    "kilolaka.fSeries": "Série F : Renaissance",
    "kilolaka.dSeries": "Série D : Énergie solaire & vitesse de la lumière",
    "kilolaka.gSeries": "Série G : L'élément qui engendre la vie",

    // Kilolaka meanings
    "ki.meaning": "Énergie intérieure — la vibration originelle",
    "lo.meaning": "Connaissance profonde ascensionnelle",
    "la.meaning": "Connaissance profonde manifestée",
    "ka.meaning": "Énergie manifestée — la vibration devient forme",
    "bi.meaning": "Être intérieur",
    "bu.meaning": "Être qui génère la vie",
    "be.meaning": "Être qui reçoit",
    "bo.meaning": "Être ascendant",
    "ba.meaning": "Être manifesté",
    "fi.meaning": "Renaissance intérieure",
    "fu.meaning": "Renaissance qui génère la vie",
    "fe.meaning": "Renaissance qui reçoit",
    "fo.meaning": "Renaissance ascendante",
    "fa.meaning": "Renaissance manifestée",
    "di.meaning": "Énergie solaire intérieure",
    "du.meaning": "Énergie solaire qui génère la vie",
    "de.meaning": "Énergie solaire qui reçoit",
    "do.meaning": "Énergie solaire ascendante",
    "da.meaning": "Énergie solaire manifestée",
    "gi.meaning": "Élément de vie intérieur",
    "gu.meaning": "Élément de vie qui génère la vie",
    "ge.meaning": "Élément de vie qui reçoit",
    "go.meaning": "Élément de vie ascendant",
    "ga.meaning": "Élément de vie manifesté",

    // Lessons page
    "lessons.eyebrow": "Zonza Lari — Leçons",
    "lessons.title": "Leçons interactives",
    "lessons.subtitle": "Apprenez le Kikongo Lari étape par étape avec du vocabulaire, des tableaux de conjugaison et des exercices interactifs.",
    "lessons.words": "mots",
    "lessons.conjugations": "conjugaisons",
    "lessons.exercises": "exercices",
    "lessons.backToLessons": "← Retour aux leçons",
    "lessons.notFound": "Leçon introuvable",
    "lessons.learn": "Apprendre",
    "lessons.startExercises": "Commencer les exercices →",
    "lessons.lessonComplete": "Leçon terminée !",
    "lessons.youGot": "Vous avez obtenu",
    "lessons.outOf": "sur",
    "lessons.correct": "correct",
    "lessons.exercise": "Exercice",
    "lessons.of": "sur",
    "lessons.correctLabel": "Correct ✓",
    "lessons.incorrectLabel": "Incorrect ✗",
    "exercises.checkAnswer": "Vérifier la réponse",
    "exercises.checkMatches": "Vérifier les correspondances",
    "exercises.typeAnswer": "Tapez votre réponse...",
    "exercises.correctAnswer": "La bonne réponse est :",
    "exercises.hint": "💡 Indice :",
    "exercises.upgrade": "Passer au Premium pour débloquer",

    // Dictionary
    "nav.dictionary": "Dictionnaire",
    "dict.eyebrow": "Buku dia nsonokono na nzonzolo Kikongo Lari — Dictionnaire",
    "dict.title": "Dictionnaire Kikongo Lari",
    "dict.subtitle": "Recherchez un mot en lari, français, anglais ou portugais et trouvez sa traduction instantanément.",
    "dict.searchPlaceholder": "Tapez un mot en lari, français, anglais ou portugais…",
    "dict.entries": "résultats",
    "dict.total": "mots au total",
    "dict.all": "Tous",
    "dict.noResults": "Aucun mot trouvé. Essayez une autre recherche.",

    // Flashcards
    "nav.flashcards": "Fiches",
    "flashcards.eyebrow": "Bitanda bia Nkanda — Fiches de révision",
    "flashcards.title": "Fiches de révision",
    "flashcards.subtitle": "Créez vos propres fiches et révisez avec la répétition espacée, comme Anki.",
    "flashcards.localWarning": "Connectez-vous pour synchroniser vos fiches entre appareils. Sans connexion, elles sont sauvegardées localement dans votre navigateur.",
    "flashcards.totalCards": "fiches au total",
    "flashcards.dueToday": "à réviser",
    "flashcards.learned": "apprises",
    "flashcards.newCards": "nouvelles",
    "flashcards.startReview": "Réviser",
    "flashcards.createCard": "Créer une fiche",
    "flashcards.browse": "Parcourir",
    "flashcards.deck": "Paquet",
    "flashcards.add": "Ajouter la fiche",
    "flashcards.tapToReveal": "Cliquez pour révéler la réponse",
    "flashcards.allDone": "Révision terminée !",
    "flashcards.comeBack": "Revenez plus tard pour continuer à apprendre.",
    "flashcards.backToDecks": "Retour",
    "flashcards.noCards": "Aucune fiche pour le moment. Créez votre première fiche !",

    // Mandombe Script
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Nsonokono Mandombe — Écriture sacrée",
    "mandombe.title": "Apprendre l'écriture Mandombe",
    "mandombe.subtitle": "Découvrez les glyphes du Mandombe, tracez-les du bout des doigts et apprenez à écrire la langue sacrée du peuple Kongo.",
    "mandombe.vowels": "Voyelles",
    "mandombe.reference": "Glyphe de référence",
    "mandombe.exampleWord": "Mot exemple",
    "mandombe.practice": "Pratiquez le tracé",
    "mandombe.traceInstruction": "Tracez le glyphe sur le canevas ci-dessous. Activez le guide pour voir la forme à reproduire.",
    "mandombe.guide": "Guide",
    "mandombe.clear": "Effacer",
    "mandombe.animate": "Animer",
    "mandombe.wordPractice": "Mots à pratiquer",

    // Translator
    "nav.translator": "Traducteur",
    "translator.eyebrow": "Nsadisi Nkanda — Traducteur",
    "translator.title": "Traducteur Kikongo Lari",
    "translator.subtitle": "Traduisez du français, anglais ou portugais vers le Kikongo Lari — avec rendu en écriture Mandombe et prononciation audio.",
    "translator.placeholder": "Tapez votre texte ici…",
    "translator.translate": "Traduire",
    "translator.hint": "Saisissez un texte et cliquez sur Traduire",
    "translator.disclaimer": "Traduction basée sur le corpus Nzo Mikanda et les travaux de Jacquot & Lumwamu sur le Kikongo Lari. Les mots hors corpus sont signalés par [?].",

    // Footer
    "footer.description": "La Maison du Savoir — préserver et enseigner le Kikongo Lari et l'écriture Mandombe pour la diaspora Kongo et le monde.",
    "footer.learnTitle": "Apprendre",
    "footer.languagesTitle": "Langues",
    "footer.copyright": "Honorer le savoir ancestral.",
  },
  en: {
    // Navbar
    "nav.learn": "Learn",
    "nav.lessons": "Lessons",
    "nav.vocabulary": "Vocabulary",
    "nav.stories": "Stories",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Sign In",
    "nav.goPremium": "Go Premium",
    "nav.managePlan": "Manage Plan",

    // Hero
    "hero.subtitle": "Nzo Mikanda — The House of Knowledge",
    "hero.description": "Discover the sacred language of the Kongo people through vocabulary, stories, and the ancestral art of Kilolaka — with translations in French, English, Portuguese, Italian, Spanish, Lingala, Greek, and Korean.",
    "hero.startLearning": "Start Learning",
    "hero.exploreVocabulary": "Explore Vocabulary",

    // LearningPaths
    "paths.eyebrow": "Your Learning Journey",
    "paths.title": "Three Paths to Mastery",
    "paths.vocab.title": "Vocabulary",
    "paths.vocab.desc": "Learn essential words and phrases in Kikongo Lari with Latin transliteration, and translations in English, French, and Portuguese.",
    "paths.vocab.items": "Greetings & Phrases,Family & People,Nature & Animals,Body & Health",
    "paths.stories.title": "Stories",
    "paths.stories.desc": "Read bilingual stories like Nsayi's adventures — immerse yourself in Kongo culture through narrative.",
    "paths.stories.items": "Nsayi at School,Nsayi in the Savanna,Cultural Tales,Children's Stories",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Explore the sacred art of decomposing Kikongo into energetic codes — language as a cosmological map.",
    "paths.kilolaka.items": "Morpheme Analysis,B & F Series,D & G Axis,Mandombe Script",

    // Vocabulary
    "vocab.eyebrow": "Mazita — Vocabulary",
    "vocab.title": "Essential Words & Phrases",
    "vocab.subtitle": "Each word comes in Kikongo Lari with translations in French, English and Portuguese — languages spoken across the Kongo diaspora.",
    "vocab.freeWords": "free words",
    "vocab.premium": "premium",
    "vocab.more": "More Words",

    // Stories
    "stories.eyebrow": "Binsamu — Stories",
    "stories.title": "Learn Through Stories",
    "stories.storySubtitle": "Nsayi at School and in the Forest",
    "stories.storyDesc": "A bilingual comic story — French, English & Portuguese",
    "stories.storyDescShort": "Nsayi at School and in the Forest",
    "stories.continue": "Continue Nsayi's Story",
    "stories.end": "The End",

    // Kilolaka
    "kilolaka.eyebrow": "Deep Knowledge",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "The art of decomposing Kikongo into sacred consciousness — where every syllable is an energetic code.",
    "kilolaka.bSeries": "B-Series: States of Being",
    "kilolaka.advanced": "Advanced Kilolaka Modules",
    "kilolaka.fSeries": "F-Series: Rebirth",
    "kilolaka.dSeries": "D-Series: Solar Energy & Speed of Light",
    "kilolaka.gSeries": "G-Series: The Element that Begets Life",

    // Kilolaka meanings
    "ki.meaning": "Inner energy — the origin vibration",
    "lo.meaning": "Ascensional deep knowledge",
    "la.meaning": "Manifested deep knowledge",
    "ka.meaning": "Manifested energy — vibration becomes form",
    "bi.meaning": "Inner being",
    "bu.meaning": "Being that generates life",
    "be.meaning": "Being that receives",
    "bo.meaning": "Ascending being",
    "ba.meaning": "Manifested being",
    "fi.meaning": "Inner rebirth",
    "fu.meaning": "Rebirth that generates life",
    "fe.meaning": "Rebirth that receives",
    "fo.meaning": "Ascending rebirth",
    "fa.meaning": "Manifested rebirth",
    "di.meaning": "Inner solar energy",
    "du.meaning": "Solar energy that generates life",
    "de.meaning": "Solar energy that receives",
    "do.meaning": "Ascending solar energy",
    "da.meaning": "Manifested solar energy",
    "gi.meaning": "Inner life element",
    "gu.meaning": "Life element that generates life",
    "ge.meaning": "Life element that receives",
    "go.meaning": "Ascending life element",
    "ga.meaning": "Manifested life element",

    // Lessons page
    "lessons.eyebrow": "Zonza Lari — Lessons",
    "lessons.title": "Interactive Lessons",
    "lessons.subtitle": "Learn Kikongo Lari step by step with vocabulary, conjugation tables, and interactive exercises.",
    "lessons.words": "words",
    "lessons.conjugations": "conjugations",
    "lessons.exercises": "exercises",
    "lessons.backToLessons": "← Back to lessons",
    "lessons.notFound": "Lesson not found",
    "lessons.learn": "Learn",
    "lessons.startExercises": "Start Exercises →",
    "lessons.lessonComplete": "Lesson Complete!",
    "lessons.youGot": "You got",
    "lessons.outOf": "out of",
    "lessons.correct": "correct",
    "lessons.exercise": "Exercise",
    "lessons.of": "of",
    "lessons.correctLabel": "Correct ✓",
    "lessons.incorrectLabel": "Incorrect ✗",
    "exercises.checkAnswer": "Check Answer",
    "exercises.checkMatches": "Check Matches",
    "exercises.typeAnswer": "Type your answer...",
    "exercises.correctAnswer": "The correct answer is:",
    "exercises.hint": "💡 Hint:",
    "exercises.upgrade": "Upgrade to unlock",

    // Dictionary
    "nav.dictionary": "Dictionary",
    "dict.eyebrow": "Buku dia nsonokono na nzonzolo Kikongo Lari — Dictionary",
    "dict.title": "Kikongo Lari Dictionary",
    "dict.subtitle": "Search a word in Lari, French, English or Portuguese and find its translation instantly.",
    "dict.searchPlaceholder": "Type a word in Lari, French, English or Portuguese…",
    "dict.entries": "results",
    "dict.total": "words in total",
    "dict.all": "All",
    "dict.noResults": "No word found. Try a different search.",

    // Flashcards
    "nav.flashcards": "Flashcards",
    "flashcards.eyebrow": "Bitanda bia Nkanda — Flashcards",
    "flashcards.title": "Flashcards",
    "flashcards.subtitle": "Create your own flashcards and review with spaced repetition, like Anki.",
    "flashcards.localWarning": "Sign in to sync your flashcards across devices. Without an account, they are saved locally in your browser.",
    "flashcards.totalCards": "total cards",
    "flashcards.dueToday": "due today",
    "flashcards.learned": "learned",
    "flashcards.newCards": "new",
    "flashcards.startReview": "Review",
    "flashcards.createCard": "Create Card",
    "flashcards.browse": "Browse",
    "flashcards.deck": "Deck",
    "flashcards.add": "Add Card",
    "flashcards.tapToReveal": "Click to reveal the answer",
    "flashcards.allDone": "All done!",
    "flashcards.comeBack": "Come back later to keep learning.",
    "flashcards.backToDecks": "Back",
    "flashcards.noCards": "No cards yet. Create your first flashcard!",

    // Mandombe Script
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Nsonokono Mandombe — Sacred Script",
    "mandombe.title": "Learn the Mandombe Script",
    "mandombe.subtitle": "Discover the Mandombe glyphs, trace them with your fingertips and learn to write the sacred language of the Kongo people.",
    "mandombe.vowels": "Vowels",
    "mandombe.reference": "Reference glyph",
    "mandombe.exampleWord": "Example word",
    "mandombe.practice": "Practice tracing",
    "mandombe.traceInstruction": "Trace the glyph on the canvas below. Toggle the guide to see the shape to reproduce.",
    "mandombe.guide": "Guide",
    "mandombe.clear": "Clear",
    "mandombe.animate": "Animate",
    "mandombe.wordPractice": "Words to practice",

    // Translator
    "nav.translator": "Translator",
    "translator.eyebrow": "Nsadisi Nkanda — Translator",
    "translator.title": "Kikongo Lari Translator",
    "translator.subtitle": "Translate from French, English or Portuguese into Kikongo Lari — with Mandombe script rendering and audio pronunciation.",
    "translator.placeholder": "Type your text here…",
    "translator.translate": "Translate",
    "translator.hint": "Enter text and click Translate",
    "translator.disclaimer": "Translation based on the Nzo Mikanda corpus and Jacquot & Lumwamu's research on Kikongo Lari. Words outside the corpus are marked with [?].",

    // Footer
    "footer.description": "The House of Knowledge — preserving and teaching Kikongo Lari and the Mandombe script for the Kongo diaspora and the world.",
    "footer.learnTitle": "Learn",
    "footer.languagesTitle": "Languages",
    "footer.copyright": "Honoring ancestral knowledge.",
  },
  pt: {
    // Navbar
    "nav.learn": "Aprender",
    "nav.lessons": "Lições",
    "nav.vocabulary": "Vocabulário",
    "nav.stories": "Histórias",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Entrar",
    "nav.goPremium": "Assinar Premium",
    "nav.managePlan": "Gerir Assinatura",

    // Hero
    "hero.subtitle": "Nzo Mikanda — A Casa do Saber",
    "hero.description": "Descubra a língua sagrada do povo Kongo através do vocabulário, das histórias e da arte ancestral do Kilolaka — com traduções em francês, inglês, português, italiano, espanhol, lingala, grego e coreano.",
    "hero.startLearning": "Começar a aprender",
    "hero.exploreVocabulary": "Explorar Vocabulário",

    // LearningPaths
    "paths.eyebrow": "A sua jornada de aprendizagem",
    "paths.title": "Três caminhos para a maestria",
    "paths.vocab.title": "Vocabulário",
    "paths.vocab.desc": "Aprenda palavras e expressões essenciais em Kikongo Lari com transliteração latina, e traduções em português, francês e inglês.",
    "paths.vocab.items": "Saudações & Expressões,Família & Pessoas,Natureza & Animais,Corpo & Saúde",
    "paths.stories.title": "Histórias",
    "paths.stories.desc": "Leia histórias bilingues como as aventuras de Nsayi — mergulhe na cultura Kongo através da narrativa.",
    "paths.stories.items": "Nsayi na escola,Nsayi na savana,Contos culturais,Histórias para crianças",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Explore a arte sagrada de decompor o Kikongo em códigos energéticos — a língua como mapa cosmológico.",
    "paths.kilolaka.items": "Análise morfológica,Séries B & F,Eixo D & G,Escrita Mandombe",

    // Vocabulary
    "vocab.eyebrow": "Mazita — Vocabulário",
    "vocab.title": "Palavras e expressões essenciais",
    "vocab.subtitle": "Cada palavra vem em Kikongo Lari com traduções em português, francês e inglês — as línguas faladas na diáspora Kongo.",
    "vocab.freeWords": "palavras gratuitas",
    "vocab.premium": "premium",
    "vocab.more": "Mais palavras",

    // Stories
    "stories.eyebrow": "Binsamu — Histórias",
    "stories.title": "Aprender através das histórias",
    "stories.storySubtitle": "Nsayi na escola e na floresta",
    "stories.storyDesc": "Uma banda desenhada bilingue — português, francês e inglês",
    "stories.storyDescShort": "Nsayi at School and in the Forest",
    "stories.continue": "Continuar a história de Nsayi",
    "stories.end": "Fim da história",

    // Kilolaka
    "kilolaka.eyebrow": "Conhecimento profundo",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "A arte de decompor o Kikongo em consciência sagrada — cada sílaba é um código energético.",
    "kilolaka.bSeries": "Série B: Estados do ser",
    "kilolaka.advanced": "Módulos Kilolaka avançados",
    "kilolaka.fSeries": "Série F: Renascimento",
    "kilolaka.dSeries": "Série D: Energia solar & velocidade da luz",
    "kilolaka.gSeries": "Série G: O elemento que gera a vida",

    // Kilolaka meanings
    "ki.meaning": "Energia interior — a vibração original",
    "lo.meaning": "Conhecimento profundo ascensional",
    "la.meaning": "Conhecimento profundo manifestado",
    "ka.meaning": "Energia manifestada — a vibração torna-se forma",
    "bi.meaning": "Ser interior",
    "bu.meaning": "Ser que gera vida",
    "be.meaning": "Ser que recebe",
    "bo.meaning": "Ser ascendente",
    "ba.meaning": "Ser manifestado",
    "fi.meaning": "Renascimento interior",
    "fu.meaning": "Renascimento que gera vida",
    "fe.meaning": "Renascimento que recebe",
    "fo.meaning": "Renascimento ascendente",
    "fa.meaning": "Renascimento manifestado",
    "di.meaning": "Energia solar interior",
    "du.meaning": "Energia solar que gera vida",
    "de.meaning": "Energia solar que recebe",
    "do.meaning": "Energia solar ascendente",
    "da.meaning": "Energia solar manifestada",
    "gi.meaning": "Elemento de vida interior",
    "gu.meaning": "Elemento de vida que gera vida",
    "ge.meaning": "Elemento de vida que recebe",
    "go.meaning": "Elemento de vida ascendente",
    "ga.meaning": "Elemento de vida manifestado",

    // Lessons page
    "lessons.eyebrow": "Zonza Lari — Lições",
    "lessons.title": "Lições interativas",
    "lessons.subtitle": "Aprenda Kikongo Lari passo a passo com vocabulário, tabelas de conjugação e exercícios interativos.",
    "lessons.words": "palavras",
    "lessons.conjugations": "conjugações",
    "lessons.exercises": "exercícios",
    "lessons.backToLessons": "← Voltar às lições",
    "lessons.notFound": "Lição não encontrada",
    "lessons.learn": "Aprender",
    "lessons.startExercises": "Começar exercícios →",
    "lessons.lessonComplete": "Lição concluída!",
    "lessons.youGot": "Acertou",
    "lessons.outOf": "de",
    "lessons.correct": "corretas",
    "lessons.exercise": "Exercício",
    "lessons.of": "de",
    "lessons.correctLabel": "Correto ✓",
    "lessons.incorrectLabel": "Incorreto ✗",
    "exercises.checkAnswer": "Verificar resposta",
    "exercises.checkMatches": "Verificar correspondências",
    "exercises.typeAnswer": "Escreva a sua resposta...",
    "exercises.correctAnswer": "A resposta correta é:",
    "exercises.hint": "💡 Dica:",
    "exercises.upgrade": "Assinar para desbloquear",

    // Dictionary
    "nav.dictionary": "Dicionário",
    "dict.eyebrow": "Buku dia nsonokono na nzonzolo Kikongo Lari — Dicionário",
    "dict.title": "Dicionário Kikongo Lari",
    "dict.subtitle": "Pesquise uma palavra em lari, francês, inglês ou português e encontre a sua tradução instantaneamente.",
    "dict.searchPlaceholder": "Escreva uma palavra em lari, francês, inglês ou português…",
    "dict.entries": "resultados",
    "dict.total": "palavras no total",
    "dict.all": "Todos",
    "dict.noResults": "Nenhuma palavra encontrada. Tente outra pesquisa.",

    // Flashcards
    "nav.flashcards": "Fichas",
    "flashcards.eyebrow": "Bitanda bia Nkanda — Fichas de revisão",
    "flashcards.title": "Fichas de revisão",
    "flashcards.subtitle": "Crie as suas próprias fichas e reveja com repetição espaçada, como o Anki.",
    "flashcards.localWarning": "Inicie sessão para sincronizar as fichas entre dispositivos. Sem conta, são guardadas localmente no navegador.",
    "flashcards.totalCards": "fichas no total",
    "flashcards.dueToday": "para rever",
    "flashcards.learned": "aprendidas",
    "flashcards.newCards": "novas",
    "flashcards.startReview": "Rever",
    "flashcards.createCard": "Criar ficha",
    "flashcards.browse": "Explorar",
    "flashcards.deck": "Baralho",
    "flashcards.add": "Adicionar ficha",
    "flashcards.tapToReveal": "Clique para revelar a resposta",
    "flashcards.allDone": "Tudo revisto!",
    "flashcards.comeBack": "Volte mais tarde para continuar a aprender.",
    "flashcards.backToDecks": "Voltar",
    "flashcards.noCards": "Ainda sem fichas. Crie a sua primeira ficha!",

    // Mandombe Script
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Nsonokono Mandombe — Escrita sagrada",
    "mandombe.title": "Aprender a escrita Mandombe",
    "mandombe.subtitle": "Descubra os glifos do Mandombe, trace-os com a ponta dos dedos e aprenda a escrever a língua sagrada do povo Kongo.",
    "mandombe.vowels": "Vogais",
    "mandombe.reference": "Glifo de referência",
    "mandombe.exampleWord": "Palavra exemplo",
    "mandombe.practice": "Pratique o traçado",
    "mandombe.traceInstruction": "Trace o glifo na tela abaixo. Ative o guia para ver a forma a reproduzir.",
    "mandombe.guide": "Guia",
    "mandombe.clear": "Limpar",
    "mandombe.animate": "Animar",
    "mandombe.wordPractice": "Palavras para praticar",

    // Translator
    "nav.translator": "Tradutor",
    "translator.eyebrow": "Nsadisi Nkanda — Tradutor",
    "translator.title": "Tradutor Kikongo Lari",
    "translator.subtitle": "Traduza do francês, inglês ou português para o Kikongo Lari — com renderização em escrita Mandombe e pronúncia áudio.",
    "translator.placeholder": "Escreva o seu texto aqui…",
    "translator.translate": "Traduzir",
    "translator.hint": "Insira um texto e clique em Traduzir",
    "translator.disclaimer": "Tradução baseada no corpus Nzo Mikanda e nos trabalhos de Jacquot & Lumwamu sobre o Kikongo Lari. Palavras fora do corpus são assinaladas com [?].",

    // Footer
    "footer.description": "A Casa do Saber — preservar e ensinar o Kikongo Lari e a escrita Mandombe para a diáspora Kongo e o mundo.",
    "footer.learnTitle": "Aprender",
    "footer.languagesTitle": "Línguas",
    "footer.copyright": "Honrando o saber ancestral.",
  },
  it: {
    // Italiano
    "nav.learn": "Imparare",
    "nav.lessons": "Lezioni",
    "nav.vocabulary": "Vocabolario",
    "nav.stories": "Storie",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Accedi",
    "nav.goPremium": "Passa a Premium",
    "nav.managePlan": "Gestisci abbonamento",
    "hero.subtitle": "Nzo Mikanda — La Casa del Sapere",
    "hero.description": "Scopri la lingua sacra del popolo Kongo attraverso il vocabolario, le storie e l'arte ancestrale del Kilolaka — con traduzioni in francese, inglese, portoghese, italiano, spagnolo, lingala, greco e coreano.",
    "hero.startLearning": "Inizia ad imparare",
    "hero.exploreVocabulary": "Esplora il vocabolario",
    "paths.eyebrow": "Il tuo percorso di apprendimento",
    "paths.title": "Tre percorsi verso la maestria",
    "paths.vocab.title": "Vocabolario",
    "paths.vocab.desc": "Impara le parole e le frasi essenziali in Kikongo Lari.",
    "paths.vocab.items": "Saluti e frasi,Famiglia e persone,Natura e animali,Corpo e salute",
    "paths.stories.title": "Storie",
    "paths.stories.desc": "Leggi storie bilingue come le avventure di Nsayi.",
    "paths.stories.items": "Nsayi a scuola,Nsayi nella savana,Racconti culturali,Storie per bambini",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Esplora l'arte sacra di scomporre il Kikongo in codici energetici.",
    "paths.kilolaka.items": "Analisi morfematica,Serie B & F,Asse D & G,Scrittura Mandombe",
    "vocab.eyebrow": "Mazita — Vocabolario",
    "vocab.title": "Parole e frasi essenziali",
    "vocab.subtitle": "Ogni parola è in Kikongo Lari con traduzioni.",
    "vocab.freeWords": "parole gratuite",
    "vocab.premium": "premium",
    "vocab.more": "Altre parole",
    "stories.eyebrow": "Binsamu — Storie",
    "stories.title": "Imparare attraverso le storie",
    "stories.storySubtitle": "Nsayi a scuola e nella foresta",
    "stories.storyDesc": "Un fumetto bilingue",
    "stories.storyDescShort": "Nsayi a scuola e nella foresta",
    "stories.continue": "Continua la storia di Nsayi",
    "stories.end": "Fine della storia",
    "kilolaka.eyebrow": "Conoscenza profonda",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "L'arte di scomporre il Kikongo nella coscienza sacra.",
    "kilolaka.bSeries": "Serie B: Stati dell'essere",
    "kilolaka.advanced": "Moduli Kilolaka avanzati",
    "kilolaka.fSeries": "Serie F: Rinascita",
    "kilolaka.dSeries": "Serie D: Energia solare",
    "kilolaka.gSeries": "Serie G: L'elemento che genera la vita",
    "ki.meaning": "Energia interiore — la vibrazione d'origine",
    "lo.meaning": "Profonda conoscenza ascensionale",
    "la.meaning": "Profonda conoscenza manifestata",
    "ka.meaning": "Energia manifestata — la vibrazione diventa forma",
    "bi.meaning": "Essere interiore",
    "bu.meaning": "Essere che genera vita",
    "be.meaning": "Essere che riceve",
    "bo.meaning": "Essere ascensionale",
    "ba.meaning": "Essere manifestato",
    "fi.meaning": "Rinascita interiore",
    "fu.meaning": "Rinascita che genera vita",
    "fe.meaning": "Rinascita che riceve",
    "fo.meaning": "Rinascita ascensionale",
    "fa.meaning": "Rinascita manifestata",
    "di.meaning": "Energia solare interiore",
    "du.meaning": "Energia solare che genera vita",
    "de.meaning": "Energia solare che riceve",
    "do.meaning": "Energia solare ascensionale",
    "da.meaning": "Energia solare manifestata",
    "gi.meaning": "Elemento vitale interiore",
    "gu.meaning": "Elemento vitale che genera vita",
    "ge.meaning": "Elemento vitale che riceve",
    "go.meaning": "Elemento vitale ascensionale",
    "ga.meaning": "Elemento vitale manifestato",
    "lessons.eyebrow": "Zonza Lari — Lezioni",
    "lessons.title": "Lezioni interattive",
    "lessons.subtitle": "Impara il Kikongo Lari passo dopo passo.",
    "lessons.words": "parole",
    "lessons.conjugations": "coniugazioni",
    "lessons.exercises": "esercizi",
    "lessons.backToLessons": "← Torna alle lezioni",
    "lessons.notFound": "Lezione non trovata",
    "lessons.learn": "Impara",
    "lessons.startExercises": "Inizia gli esercizi →",
    "lessons.lessonComplete": "Lezione completata!",
    "lessons.youGot": "Hai ottenuto",
    "lessons.outOf": "su",
    "lessons.correct": "corretto",
    "lessons.exercise": "Esercizio",
    "lessons.of": "su",
    "lessons.correctLabel": "Corretto ✓",
    "lessons.incorrectLabel": "Non corretto ✗",
    "exercises.checkAnswer": "Verifica risposta",
    "exercises.checkMatches": "Verifica corrispondenze",
    "exercises.typeAnswer": "Digita la tua risposta...",
    "exercises.correctAnswer": "La risposta corretta è:",
    "exercises.hint": "💡 Suggerimento:",
    "exercises.upgrade": "Passa a Premium per sbloccare",
    "nav.dictionary": "Dizionario",
    "dict.eyebrow": "Dizionario Kikongo Lari",
    "dict.title": "Dizionario Kikongo Lari",
    "dict.subtitle": "Cerca una parola in Lari, francese, inglese o portoghese.",
    "dict.searchPlaceholder": "Digita una parola...",
    "dict.entries": "risultati",
    "dict.total": "parole in totale",
    "dict.all": "Tutti",
    "dict.noResults": "Nessuna parola trovata.",
    "nav.flashcards": "Flashcard",
    "flashcards.eyebrow": "Flashcard di ripasso",
    "flashcards.title": "Flashcard di ripasso",
    "flashcards.subtitle": "Crea le tue flashcard e ripassa con la ripetizione spaziata.",
    "flashcards.localWarning": "Accedi per sincronizzare le tue flashcard.",
    "flashcards.totalCards": "flashcard in totale",
    "flashcards.dueToday": "da ripassare",
    "flashcards.learned": "imparate",
    "flashcards.newCards": "nuove",
    "flashcards.startReview": "Ripassa",
    "flashcards.createCard": "Crea una flashcard",
    "flashcards.browse": "Sfoglia",
    "flashcards.deck": "Mazzo",
    "flashcards.add": "Aggiungi flashcard",
    "flashcards.tapToReveal": "Tocca per rivelare la risposta",
    "flashcards.allDone": "Ripasso completato!",
    "flashcards.comeBack": "Torna più tardi.",
    "flashcards.backToDecks": "Indietro",
    "flashcards.noCards": "Nessuna flashcard per ora.",
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Scrittura sacra",
    "mandombe.title": "Impara la scrittura Mandombe",
    "mandombe.subtitle": "Scopri i glifi del Mandombe.",
    "mandombe.vowels": "Vocali",
    "mandombe.reference": "Glifo di riferimento",
    "mandombe.exampleWord": "Parola d'esempio",
    "mandombe.practice": "Pratica il tracciato",
    "mandombe.traceInstruction": "Traccia il glifo sulla tela.",
    "mandombe.guide": "Guida",
    "mandombe.clear": "Cancella",
    "mandombe.animate": "Anima",
    "mandombe.wordPractice": "Parole da praticare",
    "nav.translator": "Traduttore",
    "translator.eyebrow": "Traduttore",
    "translator.title": "Traduttore Kikongo Lari",
    "translator.subtitle": "Traduci in Kikongo Lari.",
    "translator.placeholder": "Digita il tuo testo qui…",
    "translator.translate": "Traduci",
    "translator.hint": "Inserisci un testo e clicca su Traduci",
    "translator.disclaimer": "Traduzione basata sul corpus Nzo Mikanda.",
    "footer.description": "La Casa del Sapere.",
    "footer.learnTitle": "Impara",
    "footer.languagesTitle": "Lingue",
    "footer.copyright": "Onorare il sapere ancestrale.",
  },
  ln: {
    // Lingála
    "nav.learn": "Kukumona",
    "nav.lessons": "Bikolo",
    "nav.vocabulary": "Balindaka",
    "nav.stories": "Binsamu",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Kokota",
    "nav.goPremium": "Zwa Premium",
    "nav.managePlan": "Kobongisa abonema",
    "hero.subtitle": "Nzo Mikanda — Ndako ya Mayele",
    "hero.description": "Kumona lokota ya nlongo ya bato ya Kongo na balindaka, binsamu mpe lulendo ya Kilolaka — na bafungola na Kifalansa, Lingelesi, Kipotologe, Kitaliano, Kiesipanyo, Lingála, Kigreki mpe Kikoree.",
    "hero.startLearning": "Kobanda kukumona",
    "hero.exploreVocabulary": "Kukumona balindaka",
    "paths.eyebrow": "Nzelambuka na yo ya kukumona",
    "paths.title": "Banzela misatu mpo na koyeba malamu",
    "paths.vocab.title": "Balindaka",
    "paths.vocab.desc": "Kukumona maloba mpe bibimeli ya ntina na Kikongo Lari.",
    "paths.vocab.items": "Liboso & Bibimeli,Libota & Bato,Nzinga-zinga & Banyama,Nzoto & Bokolongonu",
    "paths.stories.title": "Binsamu",
    "paths.stories.desc": "Kotanga binsamu ya nkota mibale lokola bantekele ya Nsayi.",
    "paths.stories.items": "Nsayi na kelasi,Nsayi na savane,Binsamu ya mimeseno,Binsamu ya bana",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Kukumona mayele ya nlongo ya kokabola Kikongo na bafungola ya nguya.",
    "paths.kilolaka.items": "Botali ya morphème,Séries B & F,Axe D & G,Kokoma Mandombe",
    "vocab.eyebrow": "Mazita — Balindaka",
    "vocab.title": "Maloba mpe bibimeli ya ntina",
    "vocab.subtitle": "Liloba nioso ezali na Kikongo Lari na bafungola.",
    "vocab.freeWords": "maloba ya ofele",
    "vocab.premium": "premium",
    "vocab.more": "Maloba mingi",
    "stories.eyebrow": "Binsamu — Binsamu",
    "stories.title": "Kukumona na nzela ya binsamu",
    "stories.storySubtitle": "Nsayi na kelasi mpe na zamba",
    "stories.storyDesc": "Buku ya masolo mpe ya bilili ya nkota mibale",
    "stories.storyDescShort": "Nsayi na Kelasi mpe na Zamba",
    "stories.continue": "Kobanda lisolo ya Nsayi",
    "stories.end": "Nsuka ya lisolo",
    "kilolaka.eyebrow": "Mayele ya mozindo",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "Mayele ya kokabola Kikongo na mayele ya nlongo.",
    "kilolaka.bSeries": "Série B : Bikalakala ya bomoi",
    "kilolaka.advanced": "Bacours ya Kilolaka ya lolenge ya likolo",
    "kilolaka.fSeries": "Série F : Kobotama ya sika",
    "kilolaka.dSeries": "Série D : Nguya ya moi",
    "kilolaka.gSeries": "Série G : Elementi oyo ebimisaka bomoi",
    "ki.meaning": "Eneji ya kati — libungi ya ebandeli",
    "lo.meaning": "Knowledge ya malámu ya likoló",
    "la.meaning": "Knowledge ya malámu ya monúkeli",
    "ka.meaning": "Eneji ya monúkeli — libungi eyateli monate",
    "bi.meaning": "Kaka ya kati",
    "bu.meaning": "Kaka oyo ezalisaka bomoi",
    "be.meaning": "Kaka oyo azwaka",
    "bo.meaning": "Kaka ya likoló",
    "ba.meaning": "Kaka ya monúkeli",
    "fi.meaning": "Koyángata ya kati",
    "fu.meaning": "Koyángata oyo ezalisaka bomoi",
    "fe.meaning": "Koyángata oyo azwaka",
    "fo.meaning": "Koyángata ya likoló",
    "fa.meaning": "Koyángata ya monúkeli",
    "di.meaning": "Eneji ya moyi ya kati",
    "du.meaning": "Eneji ya moyi oyo ezalisaka bomoi",
    "de.meaning": "Eneji ya moyi oyo azwaka",
    "do.meaning": "Eneji ya moyi ya likoló",
    "da.meaning": "Eneji ya moyi ya monúkeli",
    "gi.meaning": "Element ya bomoi ya kati",
    "gu.meaning": "Element ya bomoi oyo ezalisaka bomoi",
    "ge.meaning": "Element ya bomoi oyo azwaka",
    "go.meaning": "Element ya bomoi ya likoló",
    "ga.meaning": "Element ya bomoi ya monúkeli",
    "lessons.eyebrow": "Zonza Lari — Bikolo",
    "lessons.title": "Bikolo ya makomi",
    "lessons.subtitle": "Kukumona Kikongo Lari malamu na malamu.",
    "lessons.words": "maloba",
    "lessons.conjugations": "bafungola",
    "lessons.exercises": "misala",
    "lessons.backToLessons": "← Kozonga na bikolo",
    "lessons.notFound": "Kolongolola ekwenda te",
    "lessons.learn": "Kukumona",
    "lessons.startExercises": "Kobanda misala →",
    "lessons.lessonComplete": "Kolongolola esili!",
    "lessons.youGot": "Oyei",
    "lessons.outOf": "na",
    "lessons.correct": "kitoko",
    "lessons.exercise": "Mosala",
    "lessons.of": "na",
    "lessons.correctLabel": "Kitoko ✓",
    "lessons.incorrectLabel": "Mabe ✗",
    "exercises.checkAnswer": "Kotala eyano",
    "exercises.checkMatches": "Kotala bokokani",
    "exercises.typeAnswer": "Kokoma eyano na yo...",
    "exercises.correctAnswer": "Eyano ya solo ezali :",
    "exercises.hint": "💡 Elembo :",
    "exercises.upgrade": "Zwa Premium mpo na kokanga",
    "nav.dictionary": "Dictionnaire",
    "dict.eyebrow": "Dictionnaire Kikongo Lari",
    "dict.title": "Dictionnaire Kikongo Lari",
    "dict.subtitle": "Koluka liloba na Lari, Kifalansa, Lingelesi to Portugais.",
    "dict.searchPlaceholder": "Kokoma liloba...",
    "dict.entries": "bilongi",
    "dict.total": "maloba na motango",
    "dict.all": "Nioso",
    "dict.noResults": "Mabe, liloba ezali te.",
    "nav.flashcards": "Ba fiches",
    "flashcards.eyebrow": "Ba fiches ya kokumona lisusu",
    "flashcards.title": "Ba fiches ya kokumona lisusu",
    "flashcards.subtitle": "Salá ba fiches na yo moko mpe kumona lisusu na nzela ya bozalisi ya bozongeli.",
    "flashcards.localWarning": "Kokota mpo na kosangisa ba fiches na yo.",
    "flashcards.totalCards": "ba fiches na motango",
    "flashcards.dueToday": "ya kobongisa",
    "flashcards.learned": "oyebi",
    "flashcards.newCards": "ya sika",
    "flashcards.startReview": "Kobongisa",
    "flashcards.createCard": "Kosala fiche",
    "flashcards.browse": "Kotala",
    "flashcards.deck": "Paquet",
    "flashcards.add": "Kobakisa fiche",
    "flashcards.tapToReveal": "Kanya mpo na komonisa eyano",
    "flashcards.allDone": "Révision esili !",
    "flashcards.comeBack": "Zonga nsima.",
    "flashcards.backToDecks": "Kozonga",
    "flashcards.noCards": "Ba fiches ezali te sikoyo.",
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Kokoma ya nlongo",
    "mandombe.title": "Kukumona kokoma Mandombe",
    "mandombe.subtitle": "Kumona bilili ya Mandombe.",
    "mandombe.vowels": "Ba Voyelles",
    "mandombe.reference": "Bilili ya kolakisa",
    "mandombe.exampleWord": "Liloba ya kosala",
    "mandombe.practice": "Kosala kokoma",
    "mandombe.traceInstruction": "Kokoma bilili na kanvasa.",
    "mandombe.guide": "Etaleli",
    "mandombe.clear": "Kolimwisa",
    "mandombe.animate": "Kosala animation",
    "mandombe.wordPractice": "Maloba ya kosala",
    "nav.translator": "Translateg",
    "translator.eyebrow": "Translateg",
    "translator.title": "Translateg Kikongo Lari",
    "translator.subtitle": "Kofungola na Kikongo Lari.",
    "translator.placeholder": "Kokoma makomi na yo awa...",
    "translator.translate": "Kofungola",
    "translator.hint": "Kokoma makomi mpe kaya Kofungola",
    "translator.disclaimer": "Litolamona ezali na motindo ya Nzo Mikanda.",
    "footer.description": "Ndako ya Mayele.",
    "footer.learnTitle": "Kukumona",
    "footer.languagesTitle": "Bikota",
    "footer.copyright": "Kokumisa mayele ya kala.",
  },
  el: {
    // Ελληνικά
    "nav.learn": "Μάθετε",
    "nav.lessons": "Μαθήματα",
    "nav.vocabulary": "Λεξιλόγιο",
    "nav.stories": "Ιστορίες",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Σύνδεση",
    "nav.goPremium": "Αναβάθμιση σε Premium",
    "nav.managePlan": "Διαχείριση συνδρομής",
    "hero.subtitle": "Nzo Mikanda — Ο Οίκος της Γνώσης",
    "hero.description": "Ανακαλύψτε την ιερή γλώσσα του λαού Κόνγκο μέσω του λεξιλογίου, των ιστοριών και της αρχαίας τέχνης του Kilolaka — με μεταφράσεις στα γαλλικά, αγγλικά, πορτογαλικά, ιταλικά, ισπανικά, λινγκάλα, ελληνικά και κορεατικά.",
    "hero.startLearning": "Έναρξη μάθησης",
    "hero.exploreVocabulary": "Εξερευνήστε το λεξιλόγιο",
    "paths.eyebrow": "Η μαθησιακή σας διαδρομή",
    "paths.title": "Τρεις διαδρομές προς την κυριαρχία",
    "paths.vocab.title": "Λεξιλόγιο",
    "paths.vocab.desc": "Μάθετε βασικές λέξεις και φράσεις στα Kikongo Lari.",
    "paths.vocab.items": "Χαιρετισμοί & Εκφράσεις,Οικογένεια & Άνθρωποι,Φύση & Ζώα,Σώμα & Υγεία",
    "paths.stories.title": "Ιστορίες",
    "paths.stories.desc": "Διαβάστε δίγλωσσες ιστορίες, όπως τις περιπέτειες του Nsayi.",
    "paths.stories.items": "Ο Nsayi στο σχολείο,Ο Nsayi στην σαβάνα,Πολιτιστικές ιστορίες,Ιστορίες για παιδιά",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Εξερευνήστε την ιερή τέχνη της ανάλυσης του Kikongo σε ενεργειακούς κώδικες.",
    "paths.kilolaka.items": "Μορφηματική ανάλυση,Σειρές Β & F,Άξονες D & G,Γραφή Mandombe",
    "vocab.eyebrow": "Mazita — Λεξιλόγιο",
    "vocab.title": "Βασικές λέξεις και φράσεις",
    "vocab.subtitle": "Κάθε λέξη είναι στα Kikongo Lari με μεταφράσεις.",
    "vocab.freeWords": "δωρεάν λέξεις",
    "vocab.premium": "premium",
    "vocab.more": "Περισσότερες λέξεις",
    "stories.eyebrow": "Binsamu — Ιστορίες",
    "stories.title": "Μάθετε μέσα από ιστορίες",
    "stories.storySubtitle": "Nsayi στο σχολείο και στο δάσος",
    "stories.storyDesc": "Ένα δίγλωσσο κόμικ",
    "stories.storyDescShort": "Nsayi στο Σχολείο και στο Δάσος",
    "stories.continue": "Συνέχισε την ιστορία του Nsayi",
    "stories.end": "Τέλος της ιστορίας",
    "kilolaka.eyebrow": "Βαθιά Γνώση",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "Η τέχνη της ανάλυσης του Kikongo σε ιερή συνείδηση.",
    "kilolaka.bSeries": "Σειρά Β: Καταστάσεις Ύπαρξης",
    "kilolaka.advanced": "Προχωρημένες ενότητες Kilolaka",
    "kilolaka.fSeries": "Σειρά F: Αναγέννηση",
    "kilolaka.dSeries": "Σειρά D: Ηλιακή Ενέργεια",
    "kilolaka.gSeries": "Σειρά G: Το στοιχείο που γεννά τη ζωή",
    "ki.meaning": "Εσωτερική ενέργεια — η αρχική δόνηση",
    "lo.meaning": "Ανερχόμενη βαθιά γνώση",
    "la.meaning": "Εκδηλωμένη βαθιά γνώση",
    "ka.meaning": "Εκδηλωμένη ενέργεια — η δόνηση γίνεται μορφή",
    "bi.meaning": "Εσωτερική ύπαρξη",
    "bu.meaning": "Ύπαρξη που παράγει ζωή",
    "be.meaning": "Ύπαρξη που δέχεται",
    "bo.meaning": "Ανερχόμενη ύπαρξη",
    "ba.meaning": "Εκδηλωμένη ύπαρξη",
    "fi.meaning": "Εσωτερική αναγέννηση",
    "fu.meaning": "Αναγέννηση που παράγει ζωή",
    "fe.meaning": "Αναγέννηση που δέχεται",
    "fo.meaning": "Ανερχόμενη αναγέννηση",
    "fa.meaning": "Εκδηλωμένη αναγέννηση",
    "di.meaning": "Εσωτερική ηλιακή ενέργεια",
    "du.meaning": "Ηλιακή ενέργεια που παράγει ζωή",
    "de.meaning": "Ηλιακή ενέργεια που δέχεται",
    "do.meaning": "Ανερχόμενη ηλιακή ενέργεια",
    "da.meaning": "Εκδηλωμένη ηλιακή ενέργεια",
    "gi.meaning": "Εσωτερικό στοιχείο ζωής",
    "gu.meaning": "Στοιχείο ζωής που παράγει ζωή",
    "ge.meaning": "Στοιχείο ζωής που δέχεται",
    "go.meaning": "Ανερχόμενο στοιχείο ζωής",
    "ga.meaning": "Εκδηλωμένο στοιχείο ζωής",
    "lessons.eyebrow": "Zonza Lari — Μαθήματα",
    "lessons.title": "Διαδραστικά Μαθήματα",
    "lessons.subtitle": "Μάθετε το Kikongo Lari βήμα προς βήμα.",
    "lessons.words": "λέξεις",
    "lessons.conjugations": "κλίσεις",
    "lessons.exercises": "ασκήσεις",
    "lessons.backToLessons": "← Επιστροφή στα μαθήματα",
    "lessons.notFound": "Δεν βρέθηκε μάθημα",
    "lessons.learn": "Μάθετε",
    "lessons.startExercises": "Έναρξη ασκήσεων →",
    "lessons.lessonComplete": "Το μάθημα ολοκληρώθηκε!",
    "lessons.youGot": "Πετύχατε",
    "lessons.outOf": "από",
    "lessons.correct": "σωστός",
    "lessons.exercise": "Άσκηση",
    "lessons.of": "του",
    "lessons.correctLabel": "Σωστό ✓",
    "lessons.incorrectLabel": "Λάθος ✗",
    "exercises.checkAnswer": "Ελέγξτε την απάντηση",
    "exercises.checkMatches": "Ελέγξτε τις αντιστοιχίσεις",
    "exercises.typeAnswer": "Πληκτρολογήστε την απάντησή σας...",
    "exercises.correctAnswer": "Η σωστή απάντηση είναι:",
    "exercises.hint": "💡 Υπόδειξη:",
    "exercises.upgrade": "Αναβαθμίστε σε Premium για να ξεκλειδώσετε",
    "nav.dictionary": "Λεξικό",
    "dict.eyebrow": "Λεξικό Kikongo Lari",
    "dict.title": "Λεξικό Kikongo Lari",
    "dict.subtitle": "Αναζητήστε μια λέξη στα Lari, Γαλλικά, Αγγλικά ή Πορτογαλικά.",
    "dict.searchPlaceholder": "Πληκτρολογήστε μια λέξη...",
    "dict.entries": "αποτελέσματα",
    "dict.total": "λέξεις συνολικά",
    "dict.all": "Όλα",
    "dict.noResults": "Δεν βρέθηκαν λέξεις.",
    "nav.flashcards": "Κάρτες Μάθησης",
    "flashcards.eyebrow": "Κάρτες Μάθησης",
    "flashcards.title": "Κάρτες Μάθησης",
    "flashcards.subtitle": "Δημιουργήστε τις δικές σας κάρτες και αναθεωρήστε με διαλείπουσα επανάληψη.",
    "flashcards.localWarning": "Συνδεθείτε για να συγχρονίσετε τις κάρτες σας.",
    "flashcards.totalCards": "κάρτες συνολικά",
    "flashcards.dueToday": "για αναθεώρηση",
    "flashcards.learned": "έμαθαν",
    "flashcards.newCards": "νέες",
    "flashcards.startReview": "Αναθεώρηση",
    "flashcards.createCard": "Δημιουργία κάρτας",
    "flashcards.browse": "Περιήγηση",
    "flashcards.deck": "Τράπουλα",
    "flashcards.add": "Προσθήκη κάρτας",
    "flashcards.tapToReveal": "Πατήστε για να αποκαλύψετε την απάντηση",
    "flashcards.allDone": "Ολοκληρώθηκε η αναθεώρηση!",
    "flashcards.comeBack": "Επιστρέψτε αργότερα.",
    "flashcards.backToDecks": "Πίσω",
    "flashcards.noCards": "Δεν υπάρχουν κάρτες προς το παρόν.",
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Ιερή Γραφή",
    "mandombe.title": "Μάθετε τη γραφή Mandombe",
    "mandombe.subtitle": "Ανακαλύψτε τα γλύφους του Mandombe.",
    "mandombe.vowels": "Φωνήεντα",
    "mandombe.reference": "Γλύφος αναφοράς",
    "mandombe.exampleWord": "Παράδειγμα λέξης",
    "mandombe.practice": "Εξασκηθείτε στην ιχνηλάτηση",
    "mandombe.traceInstruction": "Ιχνηλατήστε τον γλύφο στον καμβά.",
    "mandombe.guide": "Οδηγός",
    "mandombe.clear": "Καθαρισμός",
    "mandombe.animate": "Κίνηση",
    "mandombe.wordPractice": "Λέξεις για εξάσκηση",
    "nav.translator": "Μεταφραστής",
    "translator.eyebrow": "Μεταφραστής",
    "translator.title": "Μεταφραστής Kikongo Lari",
    "translator.subtitle": "Μεταφράστε στα Kikongo Lari.",
    "translator.placeholder": "Πληκτρολογήστε το κείμενό σας εδώ…",
    "translator.translate": "Μετάφραση",
    "translator.hint": "Εισάγετε κείμενο και πατήστε Μετάφραση",
    "translator.disclaimer": "Μετάφραση βασισμένη στο σώμα κειμένων Nzo Mikanda.",
    "footer.description": "Ο Οίκος της Γνώσης.",
    "footer.learnTitle": "Μάθετε",
    "footer.languagesTitle": "Γλώσσες",
    "footer.copyright": "Τιμήστε την αρχαία γνώση.",
  },
  ko: {
    // 한국어
    "nav.learn": "배우기",
    "nav.lessons": "수업",
    "nav.vocabulary": "어휘",
    "nav.stories": "이야기",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "로그인",
    "nav.goPremium": "프리미엄 전환",
    "nav.managePlan": "구독 관리",
    "hero.subtitle": "Nzo Mikanda — 지식의 집",
    "hero.description": "어휘, 이야기, 그리고 고대 Kilolaka 예술을 통해 콩고 민족의 신성한 언어를 발견하세요 — 프랑스어, 영어, 포르투갈어, 이탈리아어, 스페인어, 링갈라어, 그리스어, 한국어 번역과 함께.",
    "hero.startLearning": "학습 시작",
    "hero.exploreVocabulary": "어휘 탐색",
    "paths.eyebrow": "당신의 학습 여정",
    "paths.title": "숙달을 향한 세 가지 길",
    "paths.vocab.title": "어휘",
    "paths.vocab.desc": "Kikongo Lari의 필수 단어와 구문을 배우세요.",
    "paths.vocab.items": "인사 및 표현,가족 및 사람들,자연 및 동물,신체 및 건강",
    "paths.stories.title": "이야기",
    "paths.stories.desc": "Nsayi의 모험과 같은 이중 언어 이야기를 읽어보세요.",
    "paths.stories.items": "학교의 Nsayi,사바나의 Nsayi,문화 이야기,어린이 이야기",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Kikongo를 에너지 코드로 분해하는 신성한 예술을 탐구하세요.",
    "paths.kilolaka.items": "형태론 분석,B & F 시리즈,D & G 축,Mandombe 글쓰기",
    "vocab.eyebrow": "Mazita — 어휘",
    "vocab.title": "필수 단어 및 구문",
    "vocab.subtitle": "모든 단어는 Kikongo Lari로 되어 있으며 번역도 제공됩니다.",
    "vocab.freeWords": "무료 단어",
    "vocab.premium": "프리미엄",
    "vocab.more": "더 많은 단어",
    "stories.eyebrow": "Binsamu — 이야기",
    "stories.title": "이야기를 통해 배우기",
    "stories.storySubtitle": "학교와 숲의 Nsayi",
    "stories.storyDesc": "이중 언어 만화",
    "stories.storyDescShort": "학교와 숲의 Nsayi",
    "stories.continue": "Nsayi 이야기 계속하기",
    "stories.end": "이야기 끝",
    "kilolaka.eyebrow": "심오한 지식",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "Kikongo를 신성한 의식으로 분해하는 예술.",
    "kilolaka.bSeries": "B 시리즈: 존재의 상태",
    "kilolaka.advanced": "고급 Kilolaka 모듈",
    "kilolaka.fSeries": "F 시리즈: 르네상스",
    "kilolaka.dSeries": "D 시리즈: 태양 에너지",
    "kilolaka.gSeries": "G 시리즈: 생명을 낳는 요소",
    "ki.meaning": "내면의 에너지 — 근원의 진동",
    "lo.meaning": "상승하는 깊은 지식",
    "la.meaning": "현현된 깊은 지식",
    "ka.meaning": "현현된 에너지 — 진동이 형상이 됨",
    "bi.meaning": "내면의 존재",
    "bu.meaning": "생명을 생성하는 존재",
    "be.meaning": "받는 존재",
    "bo.meaning": "상승하는 존재",
    "ba.meaning": "현현된 존재",
    "fi.meaning": "내면의 재탄생",
    "fu.meaning": "생명을 생성하는 재탄생",
    "fe.meaning": "받는 재탄생",
    "fo.meaning": "상승하는 재탄생",
    "fa.meaning": "현현된 재탄생",
    "di.meaning": "내면의 태양 에너지",
    "du.meaning": "생명을 생성하는 태양 에너지",
    "de.meaning": "받는 태양 에너지",
    "do.meaning": "상승하는 태양 에너지",
    "da.meaning": "현현된 태양 에너지",
    "gi.meaning": "내면의 생명의 원소",
    "gu.meaning": "생명을 생성하는 생명의 원소",
    "ge.meaning": "받는 생명의 원소",
    "go.meaning": "상승하는 생명의 원소",
    "ga.meaning": "현현된 생명의 원소",
    "lessons.eyebrow": "Zonza Lari — 수업",
    "lessons.title": "인터랙티브 수업",
    "lessons.subtitle": "단계별로 Kikongo Lari를 배우세요.",
    "lessons.words": "단어",
    "lessons.conjugations": "동사 변화",
    "lessons.exercises": "연습문제",
    "lessons.backToLessons": "← 수업으로 돌아가기",
    "lessons.notFound": "수업을 찾을 수 없습니다",
    "lessons.learn": "배우기",
    "lessons.startExercises": "연습 시작하기 →",
    "lessons.lessonComplete": "수업 완료!",
    "lessons.youGot": "당신은 얻었습니다",
    "lessons.outOf": "중",
    "lessons.correct": "정답",
    "lessons.exercise": "연습",
    "lessons.of": "중",
    "lessons.correctLabel": "정답 ✓",
    "lessons.incorrectLabel": "오답 ✗",
    "exercises.checkAnswer": "답변 확인",
    "exercises.checkMatches": "일치 확인",
    "exercises.typeAnswer": "답변을 입력하세요...",
    "exercises.correctAnswer": "정답은 다음과 같습니다:",
    "exercises.hint": "💡 힌트:",
    "exercises.upgrade": "잠금 해제를 위해 프리미엄으로 업그레이드",
    "nav.dictionary": "사전",
    "dict.eyebrow": "Kikongo Lari 사전",
    "dict.title": "Kikongo Lari 사전",
    "dict.subtitle": "라리, 프랑스어, 영어, 포르투갈어로 단어를 검색하세요.",
    "dict.searchPlaceholder": "단어 입력...",
    "dict.entries": "결과",
    "dict.total": "총 단어 수",
    "dict.all": "모두",
    "dict.noResults": "단어를 찾을 수 없습니다.",
    "nav.flashcards": "플래시카드",
    "flashcards.eyebrow": "플래시카드 복습",
    "flashcards.title": "플래시카드 복습",
    "flashcards.subtitle": "자신만의 플래시카드를 만들고 간격 반복 학습으로 복습하세요.",
    "flashcards.localWarning": "플래시카드를 동기화하려면 로그인하세요.",
    "flashcards.totalCards": "총 카드 수",
    "flashcards.dueToday": "오늘 복습할 카드",
    "flashcards.learned": "학습됨",
    "flashcards.newCards": "새 카드",
    "flashcards.startReview": "복습 시작",
    "flashcards.createCard": "카드 만들기",
    "flashcards.browse": "둘러보기",
    "flashcards.deck": "덱",
    "flashcards.add": "카드 추가",
    "flashcards.tapToReveal": "답변을 보려면 클릭하세요",
    "flashcards.allDone": "복습 완료!",
    "flashcards.comeBack": "나중에 다시 오십시오.",
    "flashcards.backToDecks": "뒤로",
    "flashcards.noCards": "카드가 없습니다.",
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "신성한 글자",
    "mandombe.title": "Mandombe 글자 배우기",
    "mandombe.subtitle": "Mandombe 문자를 발견하세요.",
    "mandombe.vowels": "모음",
    "mandombe.reference": "참조 문자",
    "mandombe.exampleWord": "예시 단어",
    "mandombe.practice": "쓸 때 연습하기",
    "mandombe.traceInstruction": "캔버스에 그림 문자를 그리세요.",
    "mandombe.guide": "가이드",
    "mandombe.clear": "지우기",
    "mandombe.animate": "애니메이션",
    "mandombe.wordPractice": "연습할 단어",
    "nav.translator": "번역기",
    "translator.eyebrow": "번역가",
    "translator.title": "Kikongo Lari 번역기",
    "translator.subtitle": "Kikongo Lari로 번역하세요.",
    "translator.placeholder": "여기에 텍스트를 입력하세요...",
    "translator.translate": "번역",
    "translator.hint": "텍스트를 입력하고 번역을 클릭하세요",
    "translator.disclaimer": "Nzo Mikanda 코퍼스를 기반으로 한 번역.",
    "footer.description": "지식의 집.",
    "footer.learnTitle": "배우기",
    "footer.languagesTitle": "언어",
    "footer.copyright": "선조의 지식을 존중합니다.",
  },
  es: {
    // Español
    "nav.learn": "Aprender",
    "nav.lessons": "Lecciones",
    "nav.vocabulary": "Vocabulario",
    "nav.stories": "Historias",
    "nav.kilolaka": "Kilolaka",
    "nav.signIn": "Iniciar sesión",
    "nav.goPremium": "Hazte Premium",
    "nav.managePlan": "Gestionar suscripción",
    "hero.subtitle": "Nzo Mikanda — La Casa del Saber",
    "hero.description": "Descubre la lengua sagrada del pueblo Kongo a través del vocabulario, las historias y el arte ancestral del Kilolaka — con traducciones en francés, inglés, portugués, italiano, español, lingala, griego y coreano.",
    "hero.startLearning": "Empezar a aprender",
    "hero.exploreVocabulary": "Explorar vocabulario",
    "paths.eyebrow": "Tu camino de aprendizaje",
    "paths.title": "Tres caminos hacia la maestría",
    "paths.vocab.title": "Vocabulario",
    "paths.vocab.desc": "Aprende las palabras y expresiones esenciales en Kikongo Lari.",
    "paths.vocab.items": "Saludos y expresiones,Familia y personas,Naturaleza y animales,Cuerpo y salud",
    "paths.stories.title": "Historias",
    "paths.stories.desc": "Lee historias bilingües como las aventuras de Nsayi.",
    "paths.stories.items": "Nsayi en la escuela,Nsayi en la sabana,Cuentos culturales,Historias para niños",
    "paths.kilolaka.title": "Kilolaka",
    "paths.kilolaka.desc": "Explora el arte sagrado de descomponer el Kikongo en códigos energéticos.",
    "paths.kilolaka.items": "Análisis morfémico,Series B y F,Eje D y G,Escritura Mandombe",
    "vocab.eyebrow": "Mazita — Vocabulario",
    "vocab.title": "Palabras y expresiones esenciales",
    "vocab.subtitle": "Cada palabra está en Kikongo Lari con traducciones.",
    "vocab.freeWords": "palabras gratuitas",
    "vocab.premium": "premium",
    "vocab.more": "Más palabras",
    "stories.eyebrow": "Binsamu — Historias",
    "stories.title": "Aprender con historias",
    "stories.storySubtitle": "Nsayi en la escuela y el bosque",
    "stories.storyDesc": "Un cómic bilingüe",
    "stories.storyDescShort": "Nsayi en la escuela y el bosque",
    "stories.continue": "Continuar la historia de Nsayi",
    "stories.end": "Fin de la historia",
    "kilolaka.eyebrow": "Conocimiento profundo",
    "kilolaka.title": "Kilolaka",
    "kilolaka.subtitle": "El arte de descomponer el Kikongo en conciencia sagrada.",
    "kilolaka.bSeries": "Serie B: Estados del ser",
    "kilolaka.advanced": "Módulos Kilolaka avanzados",
    "kilolaka.fSeries": "Serie F: Renacimiento",
    "kilolaka.dSeries": "Serie D: Energía solar",
    "kilolaka.gSeries": "Serie G: Elemento generador de vida",
    "ki.meaning": "Energía interior — la vibración original",
    "lo.meaning": "Conocimiento profundo ascendente",
    "la.meaning": "Conocimiento profundo manifestado",
    "ka.meaning": "Energía manifestada — la vibración se convierte en forma",
    "bi.meaning": "Ser interior",
    "bu.meaning": "Ser que genera vida",
    "be.meaning": "Ser que recibe",
    "bo.meaning": "Ser ascendente",
    "ba.meaning": "Ser manifestado",
    "fi.meaning": "Renacimiento interior",
    "fu.meaning": "Renacimiento que genera vida",
    "fe.meaning": "Renacimiento que recibe",
    "fo.meaning": "Renacimiento ascendente",
    "fa.meaning": "Renacimiento manifestado",
    "di.meaning": "Energía solar interior",
    "du.meaning": "Energía solar que genera vida",
    "de.meaning": "Energía solar que recibe",
    "do.meaning": "Energía solar ascendente",
    "da.meaning": "Energía solar manifestada",
    "gi.meaning": "Elemento vital interior",
    "gu.meaning": "Elemento vital que genera vida",
    "ge.meaning": "Elemento vital que recibe",
    "go.meaning": "Elemento vital ascendente",
    "ga.meaning": "Elemento vital manifestado",
    "lessons.eyebrow": "Zonza Lari — Lecciones",
    "lessons.title": "Lecciones interactivas",
    "lessons.subtitle": "Aprende Kikongo Lari paso a paso.",
    "lessons.words": "palabras",
    "lessons.conjugations": "conjugaciones",
    "lessons.exercises": "ejercicios",
    "lessons.backToLessons": "← Volver a las lecciones",
    "lessons.notFound": "Lección no encontrada",
    "lessons.learn": "Aprender",
    "lessons.startExercises": "Comenzar ejercicios →",
    "lessons.lessonComplete": "¡Lección completada!",
    "lessons.youGot": "Obtuviste",
    "lessons.outOf": "de",
    "lessons.correct": "correcto",
    "lessons.exercise": "Ejercicio",
    "lessons.of": "de",
    "lessons.correctLabel": "Correcto ✓",
    "lessons.incorrectLabel": "Incorrecto ✗",
    "exercises.checkAnswer": "Verificar respuesta",
    "exercises.checkMatches": "Verificar coincidencias",
    "exercises.typeAnswer": "Escribe tu respuesta...",
    "exercises.correctAnswer": "La respuesta correcta es:",
    "exercises.hint": "💡 Pista:",
    "exercises.upgrade": "Actualiza a Premium para desbloquear",
    "nav.dictionary": "Diccionario",
    "dict.eyebrow": "Diccionario Kikongo Lari",
    "dict.title": "Diccionario Kikongo Lari",
    "dict.subtitle": "Busca una palabra en lari, francés, inglés o portugués.",
    "dict.searchPlaceholder": "Escribe una palabra...",
    "dict.entries": "resultados",
    "dict.total": "palabras en total",
    "dict.all": "Todos",
    "dict.noResults": "No se encontraron palabras.",
    "nav.flashcards": "Tarjetas",
    "flashcards.eyebrow": "Tarjetas de repaso",
    "flashcards.title": "Tarjetas de repaso",
    "flashcards.subtitle": "Crea tus propias tarjetas y repasa con repetición espaciada.",
    "flashcards.localWarning": "Inicia sesión para sincronizar tus tarjetas.",
    "flashcards.totalCards": "tarjetas en total",
    "flashcards.dueToday": "para repasar",
    "flashcards.learned": "aprendidas",
    "flashcards.newCards": "nuevas",
    "flashcards.startReview": "Repasar",
    "flashcards.createCard": "Crear tarjeta",
    "flashcards.browse": "Explorar",
    "flashcards.deck": "Mazo",
    "flashcards.add": "Añadir tarjeta",
    "flashcards.tapToReveal": "Haz clic para revelar la respuesta",
    "flashcards.allDone": "¡Repaso completado!",
    "flashcards.comeBack": "Vuelve más tarde.",
    "flashcards.backToDecks": "Volver",
    "flashcards.noCards": "No hay tarjetas por ahora.",
    "nav.mandombe": "Mandombe",
    "mandombe.eyebrow": "Escritura sagrada",
    "mandombe.title": "Aprende la escritura Mandombe",
    "mandombe.subtitle": "Descubre los glifos del Mandombe.",
    "mandombe.vowels": "Vocales",
    "mandombe.reference": "Glifo de referencia",
    "mandombe.exampleWord": "Palabra de ejemplo",
    "mandombe.practice": "Practica el trazo",
    "mandombe.traceInstruction": "Traza el glifo en el lienzo.",
    "mandombe.guide": "Guía",
    "mandombe.clear": "Borrar",
    "mandombe.animate": "Animar",
    "mandombe.wordPractice": "Palabras para practicar",
    "nav.translator": "Traductor",
    "translator.eyebrow": "Traductor",
    "translator.title": "Traductor Kikongo Lari",
    "translator.subtitle": "Traduce al Kikongo Lari.",
    "translator.placeholder": "Escribe tu texto aquí…",
    "translator.translate": "Traducir",
    "translator.hint": "Introduce un texto y haz clic en Traducir",
    "translator.disclaimer": "Traducción basada en el corpus Nzo Mikanda.",
    "footer.description": "La Casa del Saber.",
    "footer.learnTitle": "Aprender",
    "footer.languagesTitle": "Idiomas",
    "footer.copyright": "Honrar el conocimiento ancestral.",
  },
};

