INSERT INTO public.translation_corrections (source_text, source_lang, target_lang, corrected_translation, notes) VALUES
('yaka', 'lari', 'fr', 'le pain de manioc', 'Vocabulaire manioc'),
('makaya', 'lari', 'fr', 'les maniocs', 'Vocabulaire manioc'),
('nkaba', 'lari', 'fr', 'les tubercules de manioc', 'Vocabulaire manioc'),
('nti ma yaka', 'lari', 'fr', 'la plante de manioc', 'Vocabulaire manioc'),
('nti ntoba', 'lari', 'fr', 'la plante de manioc', 'Vocabulaire manioc'),
('mfinda', 'lari', 'fr', 'un village isolé dans la forêt', 'Lieu'),
('muna', 'lari', 'fr', 'chaque', 'Quantifieur'),
('Muna muana na tata andi', 'lari', 'fr', 'à chaque enfant son père', 'Structure muna'),
('Nge ku nikuki', 'lari', 'fr', 'Ne bouge pas', 'Imperatif negatif'),
('Ku nikuka andi', 'lari', 'fr', 'Ne bouge pas', 'Imperatif negatif'),
('Toko', 'lari', 'fr', 'allons-y, on y va', 'Exhortatif'),
('Toko eno', 'lari', 'fr', 'allons-y, on y va', 'Exhortatif pluriel'),
('Tuendi', 'lari', 'fr', 'allons-y, on y va', 'Exhortatif'),
('Tuendi eno', 'lari', 'fr', 'allons-y, on y va', 'Exhortatif pluriel'),
('Ti toko', 'lari', 'fr', 'allons-y, on y va', 'Exhortatif'),
('Toko eno kueto', 'lari', 'fr', 'Allons-nous-en', 'Exhortatif'),
('Sidi', 'lari', 'fr', 'tu restes ?', 'Question'),
('Shidi', 'lari', 'fr', 'Est-ce que tu restes ?', 'Question - prononciation sh'),
('Nge sidi kuaku', 'lari', 'fr', 'Toi, tu restes ?', 'Question emphatique'),
('Ni tu kuenda', 'lari', 'fr', 'Viens-tu avec nous ?', 'Question'),
('Ka ni kuenda na beno ko', 'lari', 'fr', 'Je ne pars pas avec vous.', 'Negation Ka...ko'),
('Ka na kubamane ko', 'lari', 'fr', 'Je ne suis pas encore pret(e)', 'Negation Ka...ko'),
('Ka na kubamane eti ko', 'lari', 'fr', 'Je ne suis pas encore pret(e)', 'Negation Ka...eti...ko'),
('N''samu we nani ni ku tela', 'lari', 'fr', 'J''ai quelque chose à te dire.', 'Phrase courante'),
('Nsatu ye nani', 'lari', 'fr', 'J''ai faim', 'Sensation'),
('Ku lembi a ko', 'lari', 'fr', 'N''as-tu pas cuisiné ?', 'Question negative'),
('Ngana nki lembi', 'lari', 'fr', 'Qu''as-tu cuisiné ?', 'Question'),
('Lumbu tshi ka ndembi a ko', 'lari', 'fr', 'Je n''ai pas cuisiné aujourd''hui', 'Negation jour'),
('Ngana nki lembu lumbu tshi', 'lari', 'fr', 'Qu''as-tu cuisiné aujourd''hui ?', 'Question jour')
ON CONFLICT (lower(source_text), source_lang, target_lang) DO UPDATE
  SET corrected_translation = EXCLUDED.corrected_translation,
      notes = EXCLUDED.notes;